/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IngresarIndexRouteImport } from './routes/ingresar/index'
import { Route as IngresarAlertasRouteImport } from './routes/ingresar/alertas'
import { Route as IngresarAnaliticaRouteImport } from './routes/ingresar/analitica'
import { Route as IngresarConfiguracionRouteImport } from './routes/ingresar/configuracion'
import { Route as IngresarImportarRouteImport } from './routes/ingresar/importar'
import { Route as IngresarSeguimientosRouteImport } from './routes/ingresar/seguimientos'
import { Route as IngresarUsuariosRouteImport } from './routes/ingresar/usuarios'
import { Route as IngresarReproduccionIndexRouteImport } from './routes/ingresar/reproduccion/index'
import { Route as IngresarReproduccionIdRouteImport } from './routes/ingresar/reproduccion/$id'
import { Route as IngresarVacasIndexRouteImport } from './routes/ingresar/vacas/index'
import { Route as IngresarVacasVacaIdRouteImport } from './routes/ingresar/vacas/$vacaId'
import { Route as IngresarVacasNuevaRouteImport } from './routes/ingresar/vacas/nueva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarIndexRoute = IngresarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarAlertasRoute = IngresarAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarAnaliticaRoute = IngresarAnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarConfiguracionRoute = IngresarConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarImportarRoute = IngresarImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarSeguimientosRoute = IngresarSeguimientosRouteImport.update({
  id: '/seguimientos',
  path: '/seguimientos',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarUsuariosRoute = IngresarUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarReproduccionIndexRoute =
  IngresarReproduccionIndexRouteImport.update({
    id: '/reproduccion/',
    path: '/reproduccion/',
    getParentRoute: () => IngresarRoute,
  } as any)
const IngresarReproduccionIdRoute = IngresarReproduccionIdRouteImport.update({
  id: '/reproduccion/$id',
  path: '/reproduccion/$id',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarVacasIndexRoute = IngresarVacasIndexRouteImport.update({
  id: '/vacas/',
  path: '/vacas/',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarVacasVacaIdRoute = IngresarVacasVacaIdRouteImport.update({
  id: '/vacas/$vacaId',
  path: '/vacas/$vacaId',
  getParentRoute: () => IngresarRoute,
} as any)
const IngresarVacasNuevaRoute = IngresarVacasNuevaRouteImport.update({
  id: '/vacas/nueva',
  path: '/vacas/nueva',
  getParentRoute: () => IngresarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingresar': typeof IngresarRouteWithChildren
  '/login': typeof LoginRoute
  '/ingresar/alertas': typeof IngresarAlertasRoute
  '/ingresar/analitica': typeof IngresarAnaliticaRoute
  '/ingresar/configuracion': typeof IngresarConfiguracionRoute
  '/ingresar/importar': typeof IngresarImportarRoute
  '/ingresar/seguimientos': typeof IngresarSeguimientosRoute
  '/ingresar/usuarios': typeof IngresarUsuariosRoute
  '/ingresar/': typeof IngresarIndexRoute
  '/ingresar/reproduccion/$id': typeof IngresarReproduccionIdRoute
  '/ingresar/vacas/$vacaId': typeof IngresarVacasVacaIdRoute
  '/ingresar/vacas/nueva': typeof IngresarVacasNuevaRoute
  '/ingresar/reproduccion/': typeof IngresarReproduccionIndexRoute
  '/ingresar/vacas/': typeof IngresarVacasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ingresar/alertas': typeof IngresarAlertasRoute
  '/ingresar/analitica': typeof IngresarAnaliticaRoute
  '/ingresar/configuracion': typeof IngresarConfiguracionRoute
  '/ingresar/importar': typeof IngresarImportarRoute
  '/ingresar/seguimientos': typeof IngresarSeguimientosRoute
  '/ingresar/usuarios': typeof IngresarUsuariosRoute
  '/ingresar': typeof IngresarIndexRoute
  '/ingresar/reproduccion/$id': typeof IngresarReproduccionIdRoute
  '/ingresar/vacas/$vacaId': typeof IngresarVacasVacaIdRoute
  '/ingresar/vacas/nueva': typeof IngresarVacasNuevaRoute
  '/ingresar/reproduccion': typeof IngresarReproduccionIndexRoute
  '/ingresar/vacas': typeof IngresarVacasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingresar': typeof IngresarRouteWithChildren
  '/login': typeof LoginRoute
  '/ingresar/alertas': typeof IngresarAlertasRoute
  '/ingresar/analitica': typeof IngresarAnaliticaRoute
  '/ingresar/configuracion': typeof IngresarConfiguracionRoute
  '/ingresar/importar': typeof IngresarImportarRoute
  '/ingresar/seguimientos': typeof IngresarSeguimientosRoute
  '/ingresar/usuarios': typeof IngresarUsuariosRoute
  '/ingresar/': typeof IngresarIndexRoute
  '/ingresar/reproduccion/$id': typeof IngresarReproduccionIdRoute
  '/ingresar/vacas/$vacaId': typeof IngresarVacasVacaIdRoute
  '/ingresar/vacas/nueva': typeof IngresarVacasNuevaRoute
  '/ingresar/reproduccion/': typeof IngresarReproduccionIndexRoute
  '/ingresar/vacas/': typeof IngresarVacasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingresar'
    | '/login'
    | '/ingresar/alertas'
    | '/ingresar/analitica'
    | '/ingresar/configuracion'
    | '/ingresar/importar'
    | '/ingresar/seguimientos'
    | '/ingresar/usuarios'
    | '/ingresar/'
    | '/ingresar/reproduccion/$id'
    | '/ingresar/vacas/$vacaId'
    | '/ingresar/vacas/nueva'
    | '/ingresar/reproduccion/'
    | '/ingresar/vacas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ingresar/alertas'
    | '/ingresar/analitica'
    | '/ingresar/configuracion'
    | '/ingresar/importar'
    | '/ingresar/seguimientos'
    | '/ingresar/usuarios'
    | '/ingresar'
    | '/ingresar/reproduccion/$id'
    | '/ingresar/vacas/$vacaId'
    | '/ingresar/vacas/nueva'
    | '/ingresar/reproduccion'
    | '/ingresar/vacas'
  id:
    | '__root__'
    | '/'
    | '/ingresar'
    | '/login'
    | '/ingresar/alertas'
    | '/ingresar/analitica'
    | '/ingresar/configuracion'
    | '/ingresar/importar'
    | '/ingresar/seguimientos'
    | '/ingresar/usuarios'
    | '/ingresar/'
    | '/ingresar/reproduccion/$id'
    | '/ingresar/vacas/$vacaId'
    | '/ingresar/vacas/nueva'
    | '/ingresar/reproduccion/'
    | '/ingresar/vacas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngresarRoute: typeof IngresarRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar/': {
      id: '/ingresar/'
      path: '/'
      fullPath: '/ingresar/'
      preLoaderRoute: typeof IngresarIndexRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/alertas': {
      id: '/ingresar/alertas'
      path: '/alertas'
      fullPath: '/ingresar/alertas'
      preLoaderRoute: typeof IngresarAlertasRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/analitica': {
      id: '/ingresar/analitica'
      path: '/analitica'
      fullPath: '/ingresar/analitica'
      preLoaderRoute: typeof IngresarAnaliticaRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/configuracion': {
      id: '/ingresar/configuracion'
      path: '/configuracion'
      fullPath: '/ingresar/configuracion'
      preLoaderRoute: typeof IngresarConfiguracionRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/importar': {
      id: '/ingresar/importar'
      path: '/importar'
      fullPath: '/ingresar/importar'
      preLoaderRoute: typeof IngresarImportarRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/seguimientos': {
      id: '/ingresar/seguimientos'
      path: '/seguimientos'
      fullPath: '/ingresar/seguimientos'
      preLoaderRoute: typeof IngresarSeguimientosRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/usuarios': {
      id: '/ingresar/usuarios'
      path: '/usuarios'
      fullPath: '/ingresar/usuarios'
      preLoaderRoute: typeof IngresarUsuariosRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/reproduccion/': {
      id: '/ingresar/reproduccion/'
      path: '/reproduccion'
      fullPath: '/ingresar/reproduccion/'
      preLoaderRoute: typeof IngresarReproduccionIndexRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/reproduccion/$id': {
      id: '/ingresar/reproduccion/$id'
      path: '/reproduccion/$id'
      fullPath: '/ingresar/reproduccion/$id'
      preLoaderRoute: typeof IngresarReproduccionIdRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/vacas/': {
      id: '/ingresar/vacas/'
      path: '/vacas'
      fullPath: '/ingresar/vacas/'
      preLoaderRoute: typeof IngresarVacasIndexRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/vacas/$vacaId': {
      id: '/ingresar/vacas/$vacaId'
      path: '/vacas/$vacaId'
      fullPath: '/ingresar/vacas/$vacaId'
      preLoaderRoute: typeof IngresarVacasVacaIdRouteImport
      parentRoute: typeof IngresarRoute
    }
    '/ingresar/vacas/nueva': {
      id: '/ingresar/vacas/nueva'
      path: '/vacas/nueva'
      fullPath: '/ingresar/vacas/nueva'
      preLoaderRoute: typeof IngresarVacasNuevaRouteImport
      parentRoute: typeof IngresarRoute
    }
  }
}

interface IngresarRouteChildren {
  IngresarAlertasRoute: typeof IngresarAlertasRoute
  IngresarAnaliticaRoute: typeof IngresarAnaliticaRoute
  IngresarConfiguracionRoute: typeof IngresarConfiguracionRoute
  IngresarImportarRoute: typeof IngresarImportarRoute
  IngresarSeguimientosRoute: typeof IngresarSeguimientosRoute
  IngresarUsuariosRoute: typeof IngresarUsuariosRoute
  IngresarIndexRoute: typeof IngresarIndexRoute
  IngresarReproduccionIdRoute: typeof IngresarReproduccionIdRoute
  IngresarVacasVacaIdRoute: typeof IngresarVacasVacaIdRoute
  IngresarVacasNuevaRoute: typeof IngresarVacasNuevaRoute
  IngresarReproduccionIndexRoute: typeof IngresarReproduccionIndexRoute
  IngresarVacasIndexRoute: typeof IngresarVacasIndexRoute
}

const IngresarRouteChildren: IngresarRouteChildren = {
  IngresarAlertasRoute: IngresarAlertasRoute,
  IngresarAnaliticaRoute: IngresarAnaliticaRoute,
  IngresarConfiguracionRoute: IngresarConfiguracionRoute,
  IngresarImportarRoute: IngresarImportarRoute,
  IngresarSeguimientosRoute: IngresarSeguimientosRoute,
  IngresarUsuariosRoute: IngresarUsuariosRoute,
  IngresarIndexRoute: IngresarIndexRoute,
  IngresarReproduccionIdRoute: IngresarReproduccionIdRoute,
  IngresarVacasVacaIdRoute: IngresarVacasVacaIdRoute,
  IngresarVacasNuevaRoute: IngresarVacasNuevaRoute,
  IngresarReproduccionIndexRoute: IngresarReproduccionIndexRoute,
  IngresarVacasIndexRoute: IngresarVacasIndexRoute,
}

const IngresarRouteWithChildren = IngresarRoute._addFileChildren(
  IngresarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngresarRoute: IngresarRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
